name: Security AllInOne
on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
    branches:
      - develop
      - master
      - feature/*
      - release/*
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
jobs:
  build:
    name: Security Check
    runs-on:
      group: default
      labels: self-hosted
    steps:
    - name: Trigger to Insider Security
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"type": "security-allinone", "version": "v1", "repository": "${{ github.event.repository.name }}", "ref": "${{ github.head_ref || github.ref_name }}", "event_name": "${{ github.event_name }}", "event_action": "${{ github.event.action }}", "default_branch": "${{ github.event.repository.default_branch }}"}' \
        $INSECPROXY_HOOK
      env:
        INSECPROXY_HOOK: ${{ secrets.INSECPROXY_HOOK }}
